import kolesaIcon from "../images/jobIcon.svg";

export const jobs = [
  {
    id: 1,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "UI Designer",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 2,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "Frontend Developer",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 3,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "Backend Developer",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 4,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "DevOps Engineer",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 5,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "PHP developer",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 6,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "Project Manager",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 7,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "IT Helpdesk",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 8,
    company: "Kolesa Group",
    time: "Fulltime",
    salary: 1300,
    name: "iOS Developer",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
];
