import kolesaIcon from "../images/jobIcon.svg";

export const jobs = [
  {
    id: 1,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "UI Designer", nameRu: 'Дизайнер UI', nameKk: 'UI дизайнері' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 2,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "Frontend Developer", nameRu: 'Фронтенд-разработчик', nameKk: 'Frontend әзірлеушісі' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 3,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "Backend Developer", nameRu: 'Бэкенд-разработчик', nameKk: 'Backend әзірлеушісі' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 4,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "DevOps Engineer", nameRu: 'DevOps-инженер', nameKk: 'DevOps инженері' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 5,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "PHP developer", nameRu: 'PHP-разработчик', nameKk: 'PHP әзірлеушісі' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 6,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "Project Manager", nameRu: 'Руководитель проекта', nameKk: 'Жоба менеджері' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 7,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "IT Helpdesk", nameRu: 'ИТ-служба поддержки', nameKk: 'Анықтамалық қызмет' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
  {
    id: 8,
    company: "Kolesa Group",
    time: { nameEn: "Fulltime", nameRu: 'На постоянной основе', nameKk: 'Толық уақыт' },
    salary: 1300,
    name: { nameEn: "iOS Developer", nameRu: 'iOS-разработчик', nameKk: 'iOS әзірлеушісі' },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
    icon: kolesaIcon,
  },
];
