import vacancy from '../images/vacancyIcon.svg';

export const vacancies = [
    {
        id: 1,
        position: 'Backend Developert',
        company: 'EPAM Anywhere',
        location: 'Astana, Kazakhstan',
        type: 'Remote Job',
        published: '5 mins ago',
        salary: '$2000',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        features: ['Remote', 'Middle', 'Part-time'],
        icon: vacancy,
    },
    {
        id: 2,
        position: 'Backend Developert',
        company: 'EPAM Anywhere',
        location: 'Astana, Kazakhstan',
        type: 'Remote Job',
        published: '5 mins ago',
        salary: '$2000',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        features: ['Remote', 'Middle', 'Part-time'],
        icon: vacancy,
    },
    {
        id: 3,
        position: 'Backend Developert',
        company: 'EPAM Anywhere',
        location: 'Astana, Kazakhstan',
        type: 'Remote Job',
        published: '5 mins ago',
        salary: '$2000',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        features: ['Remote', 'Middle', 'Part-time'],
        icon: vacancy,
    },
    {
        id: 4,
        position: 'Backend Developert',
        company: 'EPAM Anywhere',
        location: 'Astana, Kazakhstan',
        type: 'Remote Job',
        published: '5 mins ago',
        salary: '$2000',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        features: ['Remote', 'Middle', 'Part-time'],
        icon: vacancy,
    },
    {
        id: 5,
        position: 'Backend Developert',
        company: 'EPAM Anywhere',
        location: 'Astana, Kazakhstan',
        type: 'Remote Job',
        published: '5 mins ago',
        salary: '$2000',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
        features: ['Remote', 'Middle', 'Part-time'],
        icon: vacancy,
    }
]